library(R.utils)
library(ggplot2)
library(dplyr)
library(plotly)
library(shiny)
library(shinythemes)

source("ratings_data.R")

my_ui <- fluidPage(
  theme = shinytheme("slate"),
  tabsetPanel(
    tabPanel(
      "Home",
      titlePanel("Gender and Racial Representation in the Tech Industry"),
      h4("\"In 2016, venture capitalists put $64.9 billion into male-founded startups, compared to $1.5 billion into female-founded startups\" - CNN"),
      h2("Questions to Think About"),
      p("What is the gender representation of my favorite film? Can it be improved?"),
      p("How has gender representation changed throughout time? Is the disparity shrinking?"),
      p("How does gender representation impact revenue and ratings"),
      p("What can be do to address this disparity in media?"),
      h2("Dataset"),
      p(em("Our dataset is a combination of one from IMDB and another from  Matthew Daniel's Repository, 
                which explored the number of words said by male and females in individual movies.  We had information such as movie title, 
                release date, IMDB rating, characters, character gender, character age, number of words a character spoke,  
                and revenue generated by the movie."))
    ),
    tabPanel(
      "Gender Comparison", 
      titlePanel("Gender Representation in the Tech Industry"),
      p("Type in a movie that you are interested in learning about. Compare the 
                number of words said by females characters to male characters"),
      sidebarLayout(
        sidebarPanel(
          selectizeInput("movie", "Search for a movie:", choices = NULL, multiple = FALSE, uiOutput("movieSearch"))
        ),
        mainPanel(
          plotlyOutput("charwords"), p(textOutput("sumStatement"))
        )
      ),
      h3("Total there are 18821 characters and 17367445 spoken in this dataset. There are 5657 
              female characters that say a total of 4891976 words. There are 13161 male characters 
              that say a total of 12474717 words. Male characters make up around 70% of the characters and 
               say 72% of the words. Female characters make up 30% of the characters and say 28% of the words")
    ),
    tabPanel(
      "Racial Comparison", 
      titlePanel("Racial Representation in the Tech Industry"),
      p("Type in a movie that you are interested in learning about. Compare the 
                number of words said by females characters to male characters"),
      sidebarLayout(
        sidebarPanel(
          selectizeInput("movie", "Search for a movie:", choices = NULL, multiple = FALSE, uiOutput("movieSearch"))
        ),
        mainPanel(
          plotlyOutput("charwords"), p(textOutput("sumStatement"))
        )
      ),
      h3("Total there are 18821 characters and 17367445 spoken in this dataset. There are 5657 
              female characters that say a total of 4891976 words. There are 13161 male characters 
              that say a total of 12474717 words. Male characters make up around 70% of the characters and 
               say 72% of the words. Female characters make up 30% of the characters and say 28% of the words")
    ),
    tabPanel(
      "Harassment Reports",
      titlePanel("Incidents involving Sexual Harassment for Large Tech Companies"),
      p("\"There is a lot of talk in the industry about teaching girls to code and recruiting more women for tech jobs.
        But without addressing sexual harassment and other forms of bias,
        tech companies won't be able to attract a more diverse workforce and retain those entering the field.\" - Ina Fried"),
      p("In this section, we want to identify and bring awareness to major tech companies that have dealt with sexual harassment cases.
        For our viewers, we want to arm you with the knowledge on how these companies have dealt with sexual harassment cases in the past.
        To the victims that have had a similar experience, we want to let you know that you're not alone."),
      
      h2("Google"),
      p(em("\"Shareholders file lawsuit against Google over payouts to executives accused of sexual harassment\" - Casey Newton")),
      p(em("")),
      
      h2("Facebook"),
      p(em("\"Chia Hong, the former Facebook employee who sued [Facebook], 
        claims she suffered three years of harassment during stints as a program manager and technology partner.\" - Tom Huddleston Jr.")),
      p(em("\"Facebook said on Friday that it would no longer force employees to settle sexual harassment claims in private arbitration,
        making it the latest technology company to do away with a practice that critics say has stacked the deck against victims of harassment.\"
        - Daisuke Wakabayashi and Jessica Silver-Greenberg")),
      
      h2("Amazon"),
      p(em("\"Amazon Studios Chief Roy Price Suspended Amid Sexual-Harassment Accusations\" - Kim Masters")),
      
      h2("An Important Statistic"),
      p("\"Certainly, the largest percentage of people — 85% — said they'd been harassed by a superior,
      but 75% said they had been harassed by an equal, and 30% said they were targeted by a subordinate.\""),
      
      h2("Citations"),
      p("https://www.axios.com/tech-sexual-harassment-women-silicon-valley-1fa55b9c-2997-49cc-a869-d3cb7334a543.html"),
      p("https://www.theverge.com/2019/1/10/18177445/google-shareholder-lawsuit-sexual-harassment-andy-rubin-me-too"),
      p("http://fortune.com/2015/03/18/facebook-sex-discrimination/?fbclid=IwAR3unljDmmjrnNz247n01CdYrLzVn6ZXnfhfTjmZki6Jgbpcnpy3iUChiTI"),
      p("https://www.nytimes.com/2018/11/09/technology/facebook-arbitration-harassment.html?fbclid=IwAR0Oaa7Uh1e-xSYOj_iPhTSP9o8nI9oTLkt9GEDM_01dXO1drC7VVZ3Nw6c"),
      p("https://www.thedailybeast.com/amazon-studios-exec-accused-of-sexual-harassment?fbclid=IwAR1e1CGfBUQ1W3DcE4PhTbrtI1eSyRqsLYKQDqvxfYC2Q7qrKmmP78ZVWDA"),
      p("https://www.buzzfeednews.com/article/doree/we-surveyed-hundreds-about-techs-harassment-problem?fbclid=IwAR21OBTodCfe3SF55VeKtrJ7pCt1RBrZnS8Jek-gTPQwYsnzmZb5JKdaCVQ")
    ),
    tabPanel(
      "Conclusion",
      titlePanel(
        h1("Overall Analysis")
      ),
      p("")
    )
  )
)
shinyUI(my_ui)