library(R.utils)
library(ggplot2)
library(dplyr)
library(plotly)
library(shiny)
library(shinythemes)

source("ratings_data.R")

my_ui <- fluidPage(
  theme = shinytheme("superhero"),
  tabsetPanel(
    tabPanel(
      "Home",
      titlePanel("Gender and Racial Representation in the Tech Industry"),
      h4("\"In 2016, venture capitalists put $64.9 billion into male-founded startups, compared to $1.5 billion into female-founded startups\" - CNN"),
      h2("Questions to Think About"),
      p("What is the gender representation of my favorite film? Can it be improved?"),
      p("How has gender representation changed throughout time? Is the disparity shrinking?"),
      p("How does gender representation impact revenue and ratings"),
      p("What can be do to address this disparity in media?"),
      h2("Dataset"),
      p(em("Our dataset is a combination of one from IMDB and another from  Matthew Daniel's Repository, 
                which explored the number of words said by male and females in individual movies.  We had information such as movie title, 
                release date, IMDB rating, characters, character gender, character age, number of words a character spoke,  
                and revenue generated by the movie."))
    ),
    tabPanel(
      "Gender Comparison", 
      titlePanel("Gender Representation in the Tech Industry"),
      p("Type in a movie that you are interested in learning about. Compare the 
                number of words said by females characters to male characters"),
      sidebarLayout(
        sidebarPanel(
          selectizeInput("movie", "Search for a movie:", choices = NULL, multiple = FALSE, uiOutput("movieSearch"))
        ),
        mainPanel(
          plotlyOutput("charwords"), p(textOutput("sumStatement"))
        )
      ),
      h3("Total there are 18821 characters and 17367445 spoken in this dataset. There are 5657 
              female characters that say a total of 4891976 words. There are 13161 male characters 
              that say a total of 12474717 words. Male characters make up around 70% of the characters and 
               say 72% of the words. Female characters make up 30% of the characters and say 28% of the words")
    ),
    tabPanel(
      "Raical Comparison", 
      titlePanel("Racial Representation in the Tech Industry"),
      p("Type in a movie that you are interested in learning about. Compare the 
                number of words said by females characters to male characters"),
      sidebarLayout(
        sidebarPanel(
          selectizeInput("movie", "Search for a movie:", choices = NULL, multiple = FALSE, uiOutput("movieSearch"))
        ),
        mainPanel(
          plotlyOutput("charwords"), p(textOutput("sumStatement"))
        )
      ),
      h3("Total there are 18821 characters and 17367445 spoken in this dataset. There are 5657 
              female characters that say a total of 4891976 words. There are 13161 male characters 
              that say a total of 12474717 words. Male characters make up around 70% of the characters and 
               say 72% of the words. Female characters make up 30% of the characters and say 28% of the words")
    ),
    tabPanel(
      "Harassment Reports",
      titlePanel("Incidents involving Sexual Harassment for Large Tech Companies"),
      p("\"There is a lot of talk in the industry about teaching girls to code and recruiting more women for tech jobs.
        But without addressing sexual harassment and other forms of bias,
        tech companies won't be able to attract a more diverse workforce and retain those entering the field.\" - Ina Fried"),
      
      h2("Google"),
      h4(em("\"Shareholders file lawsuit against Google over payouts to executives accused of sexual harassment\" - Casey Newton")),
      h4(em("")),
      
      h2("Facebook"),
      p(""),
      
      h2("Amazon"),
      p(""), 
      
      h2("Citations"),
      p("https://www.axios.com/tech-sexual-harassment-women-silicon-valley-1fa55b9c-2997-49cc-a869-d3cb7334a543.html"),
      p("https://www.theverge.com/2019/1/10/18177445/google-shareholder-lawsuit-sexual-harassment-andy-rubin-me-too")
    ),
    tabPanel(
      "Conclusion",
      titlePanel(h1("Overall Analysis")),
      p("Through our visualizations to becomes clear that there is gender disparity between males and females in movies.
      A further analysis seems to show that while this difference does exist, the arguments for why it exists does not make sense. 
      A common argument is that female-led films are received less positively by the audience,
      but looking at the data male-led movies and female-led movies receive similar scores on IMDB. 
      While male-led movies do make more money at the box office, there exists a substantial gap between the number of male-led and female-led movies.
      But, if male-led and female-led movies recieve similar reception by the audience why is that male-led movies make more money?
      Do more people go to male-led movies than female-led movies? 
      Could it be that male-led movies have both a female and male audience, but female-led movies only have a female audience?
      We can't answer that question with our current analysis and data, 
      but our work reveals that there is a clear difference between gender representation in movies.
      Understanding and recognizing that there is a problem is only the first step in finding solutions"),
      h2("Future Explorations"),
      p("To further explore this topic, it would be necessary to look at who is making the movies. 
      What are the genders of the producers, screenwriters, and directors? 
      How is that correlated to the representation that ends up in the film? 
      Furthermore, we could look at film goers and learn about the gender make-up of a film's audience and what they think of the movie. 
      We can try to determine maybe if there is a bias for or against female-led films, based on this data.")
    )
  )
)
shinyUI(my_ui)